package co.micol.prj;

import co.micol.prj.Member;
import java.util.List;

public interface MemberMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MEMBER
     *
     * @mbg.generated Wed Aug 04 14:24:14 KST 2021
     */
    int insert(Member record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MEMBER
     *
     * @mbg.generated Wed Aug 04 14:24:14 KST 2021
     */
    List<Member> selectAll();
}