package co.micol.prj;

import java.util.Date;

public class Sns {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SNS.SNO
     *
     * @mbg.generated Wed Aug 04 14:24:14 KST 2021
     */
    private Short sno;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SNS.SWRITER
     *
     * @mbg.generated Wed Aug 04 14:24:14 KST 2021
     */
    private String swriter;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SNS.SDATE
     *
     * @mbg.generated Wed Aug 04 14:24:14 KST 2021
     */
    private Date sdate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SNS.STITLE
     *
     * @mbg.generated Wed Aug 04 14:24:14 KST 2021
     */
    private String stitle;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SNS.SCONTENTS
     *
     * @mbg.generated Wed Aug 04 14:24:14 KST 2021
     */
    private String scontents;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SNS.SANO
     *
     * @mbg.generated Wed Aug 04 14:24:14 KST 2021
     */
    private Short sano;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SNS.SNO
     *
     * @return the value of SNS.SNO
     *
     * @mbg.generated Wed Aug 04 14:24:14 KST 2021
     */
    public Short getSno() {
        return sno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SNS.SNO
     *
     * @param sno the value for SNS.SNO
     *
     * @mbg.generated Wed Aug 04 14:24:14 KST 2021
     */
    public void setSno(Short sno) {
        this.sno = sno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SNS.SWRITER
     *
     * @return the value of SNS.SWRITER
     *
     * @mbg.generated Wed Aug 04 14:24:14 KST 2021
     */
    public String getSwriter() {
        return swriter;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SNS.SWRITER
     *
     * @param swriter the value for SNS.SWRITER
     *
     * @mbg.generated Wed Aug 04 14:24:14 KST 2021
     */
    public void setSwriter(String swriter) {
        this.swriter = swriter;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SNS.SDATE
     *
     * @return the value of SNS.SDATE
     *
     * @mbg.generated Wed Aug 04 14:24:14 KST 2021
     */
    public Date getSdate() {
        return sdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SNS.SDATE
     *
     * @param sdate the value for SNS.SDATE
     *
     * @mbg.generated Wed Aug 04 14:24:14 KST 2021
     */
    public void setSdate(Date sdate) {
        this.sdate = sdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SNS.STITLE
     *
     * @return the value of SNS.STITLE
     *
     * @mbg.generated Wed Aug 04 14:24:14 KST 2021
     */
    public String getStitle() {
        return stitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SNS.STITLE
     *
     * @param stitle the value for SNS.STITLE
     *
     * @mbg.generated Wed Aug 04 14:24:14 KST 2021
     */
    public void setStitle(String stitle) {
        this.stitle = stitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SNS.SCONTENTS
     *
     * @return the value of SNS.SCONTENTS
     *
     * @mbg.generated Wed Aug 04 14:24:14 KST 2021
     */
    public String getScontents() {
        return scontents;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SNS.SCONTENTS
     *
     * @param scontents the value for SNS.SCONTENTS
     *
     * @mbg.generated Wed Aug 04 14:24:14 KST 2021
     */
    public void setScontents(String scontents) {
        this.scontents = scontents;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SNS.SANO
     *
     * @return the value of SNS.SANO
     *
     * @mbg.generated Wed Aug 04 14:24:14 KST 2021
     */
    public Short getSano() {
        return sano;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SNS.SANO
     *
     * @param sano the value for SNS.SANO
     *
     * @mbg.generated Wed Aug 04 14:24:14 KST 2021
     */
    public void setSano(Short sano) {
        this.sano = sano;
    }
}