package co.micol.prj;

import co.micol.prj.Sns;
import java.util.List;

public interface SnsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SNS
     *
     * @mbg.generated Wed Aug 04 14:24:14 KST 2021
     */
    int deleteByPrimaryKey(Short sno);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SNS
     *
     * @mbg.generated Wed Aug 04 14:24:14 KST 2021
     */
    int insert(Sns record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SNS
     *
     * @mbg.generated Wed Aug 04 14:24:14 KST 2021
     */
    Sns selectByPrimaryKey(Short sno);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SNS
     *
     * @mbg.generated Wed Aug 04 14:24:14 KST 2021
     */
    List<Sns> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SNS
     *
     * @mbg.generated Wed Aug 04 14:24:14 KST 2021
     */
    int updateByPrimaryKey(Sns record);
}